# Generated by Django 2.1.1 on 2018-09-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikkel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_nr', models.IntegerField(verbose_name='Artikkelnummer')),
                ('pris', models.IntegerField(verbose_name='Pris')),
                ('leveringstid', models.IntegerField(verbose_name='Leveringstid i uker')),
                ('sist_byttet', models.DateField(verbose_name='Sist byttet')),
                ('type_levetid', models.CharField(choices=[('Gjenværende levetid', 'Gjenværende levetid'), ('Forventet levetid', 'Forventet levetid')], max_length=30)),
                ('levetid', models.IntegerField(verbose_name='Levetid i år')),
            ],
            options={
                'verbose_name_plural': 'artikler',
                'ordering': ['art_nr'],
            },
        ),
    ]
