# Generated by Django 2.1.1 on 2018-09-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikkel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_nr', models.IntegerField(verbose_name='Artikkelnummer')),
                ('tid_for_vurdering', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tid for vurdering')),
                ('pris', models.IntegerField(verbose_name='Pris')),
                ('lagerkost_aar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Årlig lagerkost')),
                ('kostnad_ved_defekt', models.IntegerField(blank=True, null=True, verbose_name='Daglig kostnad ved defekt')),
                ('leveringstid', models.IntegerField(verbose_name='Leveringstid i uker')),
                ('sist_byttet', models.DateField(verbose_name='Sist byttet')),
                ('tid_inne', models.IntegerField(blank=True, null=True, verbose_name='Tid inne')),
                ('planlagt_byttet', models.DateField(blank=True, null=True, verbose_name='Planlagt byttet')),
                ('skal_byttes', models.CharField(blank=True, choices=[('Sikkert', 'Sikkert'), ('Usikkert', 'Usikkert')], max_length=10, null=True, verbose_name='Sikkert/usikkert bytte')),
                ('type_levetid', models.CharField(choices=[('Gjenværende levetid', 'Gjenværende levetid'), ('Forventet levetid', 'Forventet levetid')], max_length=30)),
                ('levetid_aar', models.IntegerField(null=True, verbose_name='Levetid i år')),
                ('levetid', models.IntegerField(blank=True, null=True, verbose_name='Levetid i dager')),
                ('forbrenning_konsekvens', models.BooleanField(default=False, null=True)),
                ('forbrenning_grad', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('stromprod_konsekvens', models.BooleanField(default=False, null=True)),
                ('stromprod_grad', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('kost_alternativ_drift', models.IntegerField(blank=True, null=True, verbose_name='Kostnad (per døgn) ved alternativ drift')),
                ('lager', models.BooleanField(blank=True, default=False, null=True, verbose_name='Skal bestilles')),
                ('kritisk_dato', models.DateField(blank=True, null=True, verbose_name='Kritisk dato')),
            ],
            options={
                'verbose_name_plural': 'artikler',
                'ordering': ['art_nr'],
            },
        ),
        migrations.CreateModel(
            name='FastParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('Lagerkost', 'Lagerkost'), ('Kost ved driftsstans (gatefee)', 'Kost ved driftsstans (gatefee)'), ('Kost ved stans i strømproduksjon', 'Kost ved stans i strømproduksjon'), ('Weibull Shape Parameter', 'Weibull Shape Parameter'), ('Weibull Scale Parameter', 'Weibull Scale Parameter'), ('Avkastningskrav', 'Avkastningskrav')], max_length=40, null=True, unique=True)),
                ('parameter_verdi', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Faste parametere',
            },
        ),
        migrations.CreateModel(
            name='Konsekvenser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konsekvens', models.CharField(max_length=30)),
            ],
        ),
    ]
