# Generated by Django 2.1.1 on 2018-09-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkel',
            name='type_konsekvens',
            field=models.CharField(choices=[('Stans i forbrenning', 'Stans i forbrenning'), ('Stans i strømproduksjon', 'Stans i strømproduksjon'), ('Alternativ drift', 'Alternativ drift'), ('Ingen avbrudd', 'Ingen avbrudd')], max_length=30, null=True),
        ),
    ]
