# Generated by Django 2.1.1 on 2018-09-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikkel',
            name='forbrenning_konsekvens',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='stromprod_konsekvens',
            field=models.BooleanField(default=False),
        ),
    ]
