# Generated by Django 2.1.1 on 2018-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0002_artikkel_type_konsekvens'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkel',
            name='redusert_drift',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
