# Generated by Django 2.1.1 on 2018-09-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0003_artikkel_redusert_drift'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkel',
            name='kost_alternativ_drift',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kostnad (per døgn) ved alternativ drift'),
        ),
    ]
