# Generated by Django 2.1.1 on 2018-09-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0003_auto_20180911_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkel',
            name='dtkost',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='forbrenning_grad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='forbrenning_konsekvens',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='stromprod_grad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='stromprod_konsekvens',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fastparameter',
            name='parameter',
            field=models.CharField(choices=[('Lagerkost', 'Lagerkost'), ('Kost ved driftsstans (gatefee)', 'Kost ved driftsstans (gatefee)'), ('Variabel driftskostnad per døgn', 'Variabel driftskostnad per døgn'), ('Kost ved stans i strømproduksjon', 'Kost ved stans i strømproduksjon'), ('Weibull Shape Parameter', 'Weibull Shape Parameter'), ('Weibull Scale Parameter', 'Weibull Scale Parameter'), ('Avkastningskrav', 'Avkastningskrav')], max_length=40, null=True, unique=True),
        ),
    ]
