# Generated by Django 2.1.1 on 2018-09-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0004_artikkel_kost_alternativ_drift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikkel',
            name='redusert_drift',
            field=models.CharField(blank=True, choices=[('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%')], max_length=5, null=True),
        ),
    ]
