# Generated by Django 2.1.1 on 2018-09-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0005_auto_20180906_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikkel',
            name='type_konsekvens',
            field=models.CharField(choices=[('Stans i forbrenning', 'Stans i forbrenning'), ('Stans i strømproduksjon', 'Stans i strømproduksjon'), ('Alternativ/justert drift', 'Alternativ/justert drift'), ('Ingen avbrudd', 'Ingen avbrudd')], max_length=30, null=True),
        ),
    ]
