# Generated by Django 2.1.1 on 2018-09-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0006_auto_20180912_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkel',
            name='tid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
