# Generated by Django 2.1.1 on 2018-09-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0008_artikkel_vektet_lagerkost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
