# Generated by Django 2.1.1 on 2018-09-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0008_fastparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='fastparameter',
            options={'verbose_name_plural': 'Faste parametere'},
        ),
    ]
