# Generated by Django 2.1.1 on 2018-09-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0010_auto_20180906_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='full_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
