# Generated by Django 2.1.1 on 2018-09-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0011_name_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.RemoveField(
            model_name='fastparameter',
            name='driftsavbrudd_kost',
        ),
        migrations.RemoveField(
            model_name='fastparameter',
            name='lagerkost',
        ),
        migrations.RemoveField(
            model_name='fastparameter',
            name='stromprod_kost',
        ),
        migrations.AddField(
            model_name='fastparameter',
            name='parameter',
            field=models.CharField(choices=[('Lagerkost', 'Lagerkost'), ('Kost ved driftsstans (gatefee)', 'Kost ved driftsstans (gatefee)'), ('Kost ved stans i strømproduksjon', 'Kost ved stans i strømproduksjon')], max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fastparameter',
            name='parameter_verdi',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
