# Generated by Django 2.1.1 on 2018-09-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0012_auto_20180907_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkel',
            name='lagerkost_aar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
