# Generated by Django 2.1.1 on 2018-09-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0013_artikkel_lagerkost_aar'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkel',
            name='tid_for_vurdering',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='lagerkost_aar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Årlig lagerkost'),
        ),
    ]
