# Generated by Django 2.1.1 on 2018-09-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0014_auto_20180907_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkel',
            name='tid_inne',
            field=models.IntegerField(null=True, verbose_name='Tid inne'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='tid_for_vurdering',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tid for vurdering'),
        ),
    ]
