# Generated by Django 2.1.1 on 2018-09-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0015_auto_20180907_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkel',
            name='kostnad_ved_defekt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Daglig kostnad ved defekt'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='tid_inne',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tid inne'),
        ),
    ]
