# Generated by Django 2.1.1 on 2018-09-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0016_auto_20180907_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konsekvenser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konsekvens', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='artikkel',
            name='redusert_drift',
        ),
        migrations.RemoveField(
            model_name='artikkel',
            name='type_konsekvens',
        ),
        migrations.AddField(
            model_name='artikkel',
            name='forbrenning_grad',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='forbrenning_konsekvens',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='stromprod_grad',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='stromprod_konsekvens',
            field=models.BooleanField(null=True),
        ),
    ]
