# Generated by Django 2.1.1 on 2018-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0017_auto_20180907_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkel',
            name='levetid_aar',
            field=models.IntegerField(null=True, verbose_name='Levetid i år'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='levetid',
            field=models.IntegerField(null=True, verbose_name='Levetid i dager'),
        ),
    ]
