# Generated by Django 2.1.1 on 2018-09-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0018_auto_20180907_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikkel',
            name='levetid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Levetid i dager'),
        ),
        migrations.AlterField(
            model_name='fastparameter',
            name='parameter',
            field=models.CharField(choices=[('Lagerkost', 'Lagerkost'), ('Kost ved driftsstans (gatefee)', 'Kost ved driftsstans (gatefee)'), ('Kost ved stans i strømproduksjon', 'Kost ved stans i strømproduksjon'), ('Weibull Shape Parameter', 'Weibull Shape Parameter'), ('Weibull Scale Parameter', 'Weibull Scale Parameter')], max_length=40, null=True, unique=True),
        ),
    ]
