# Generated by Django 2.1.1 on 2018-09-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0019_auto_20180907_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkel',
            name='kritisk_dato',
            field=models.DateField(blank=True, null=True, verbose_name='Kritisk dato'),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='lager',
            field=models.BooleanField(blank=True, null=True, verbose_name='Lagervurdering'),
        ),
    ]
