# Generated by Django 2.1.1 on 2018-09-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0020_auto_20180907_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikkel',
            name='forbrenning_konsekvens',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='lager',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Lagervurdering'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='stromprod_konsekvens',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
