# Generated by Django 2.1.1 on 2018-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0021_auto_20180907_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikkel',
            name='lager',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Skal bestilles'),
        ),
        migrations.AlterField(
            model_name='fastparameter',
            name='parameter',
            field=models.CharField(choices=[('Lagerkost', 'Lagerkost'), ('Kost ved driftsstans (gatefee)', 'Kost ved driftsstans (gatefee)'), ('Kost ved stans i strømproduksjon', 'Kost ved stans i strømproduksjon'), ('Weibull Shape Parameter', 'Weibull Shape Parameter'), ('Weibull Scale Parameter', 'Weibull Scale Parameter'), ('Avkastningskrav', 'Avkastningskrav')], max_length=40, null=True, unique=True),
        ),
    ]
